// Code generated by cmd/extension-protocol-gen; DO NOT EDIT.

package protocol

// GeneratedSchemaHash is the SHA-256 of schema.generated.json. Handshake
// comparisons use this constant; protocol tests independently recompute it
// from CanonicalSchemaBytes to reject stale generated artifacts.
const GeneratedSchemaHash = "sha256:74469060337755e305098bc21d75b0255028e12043f411a4408f2344be83548f"
