import {
  Bookmark,
  Check,
  CircleHelp,
  FilePen,
  FileText,
  Folder,
  FolderSearch,
  GitBranch,
  Globe,
  Hash,
  ListChecks,
  Plug,
  ScanSearch,
  Search,
  ShieldCheck,
  Shrink,
  SquareCheck,
  SquareTerminal,
  Target,
  type LucideIcon,
} from "lucide-react";

const BY_TOOL: Record<string, LucideIcon> = {
  web_search: Globe,
  web_fetch: Globe,
  task: GitBranch,
  edit_file: FilePen,
  write_file: FilePen,
  multi_edit: FilePen,
  use_capability: Plug,
  remember: Bookmark,
  bash: SquareTerminal,
  bash_output: SquareTerminal,
  kill_shell: SquareTerminal,
  wait: SquareTerminal,
  read_file: FileText,
  grep: Search,
  glob: FolderSearch,
  ls: Folder,
  todo_write: ListChecks,
  code_index: Hash,
  complete_step: SquareCheck,
  compress: Shrink,
  update_goal: Target,
  review_report: ScanSearch,
  guardian_assessment: ShieldCheck,
  ask: CircleHelp,
};

export const iconFor = (tool: string): LucideIcon => BY_TOOL[tool] ?? FileText;

export const DONE = Check;
